zuul:
  prefix: /pump
  routes:
    asset-engineering-service:
      path: /engg/**
      serviceId: ASSET-ENGINEERING-SERVICE
    asset-config-service:
      path: /config/**
      serviceId: ASSET-CONFIG-SERVICE
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
      
spring:
  application:
    name: pump-gateway
    
server:
  port: 8001
  
 